spring:
    application:
        name: AnimeChallenges
    datasource:
        url: jdbc:postgresql://localhost:5432/anime_challenges
        username: postgres
        password: password
    main:
        banner-mode: off

jwt:
    secretKey: xyzqhpQYnQtFXqigYEeefzwxsglwfqbnAdvhNdQPrBwIVIRKgyzZiiSraYMwslij
    lifetime: 900000 # 15 min
    refreshTokenDurationMs: 604800000 # 7 days

file:
    upload-dir: /var/anime-challenges/data
    base-url: /api/v1/media/

media:
    max-uploaded-media: 5